#cache:
#  hazelcast:
#    instance-name: 'cache-support'
#    management-enabled: false
#    map-settings:
#      property-relations:
#        type-id: 1
#        backup-count: 0
#        async-backup-count: 1
#        max-size: 5_000_000
#        max-size-policy: PER_NODE
#        time-to-live-seconds: 300 # 5 min
#        class-name: # com.fistkim.DTO
#        statistics-enabled: true
