spring:
  application:
    name: 'sample-app'

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

#logging:
#  level:
#    root: debug

