server:
  port: 8070

spring:
  config:
    activate:
      on-profile: local

# security users
security:
  user:
    actuator:
      username: actuator
      password: 200
    admin:
      username: admin
      password: 200

# eureka
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${security.user.actuator.username}:${security.user.actuator.password}@localhost:8761/eureka/
    enabled: false

