server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local

# security users
security:
  user:
    actuator:
      username: actuator
      password: 200
    admin:
      username: admin
      password: 200

# eureka
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20

    metadata-map:
      user.name: ${security.user.actuator.username}
      user.password: ${security.user.actuator.password}

  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/
    healthcheck:
      enabled: true
